### ISSUE TITLE
the immersive components english file has two `.json` extensions

### ISSUE THREAD

**Issue by woodiertexas** [SkyrimLL/Cyberpunk2077#165]
https://github.com/SkyrimLL/Cyberpunk2077/blob/main/ImmersiveComponents/source/raw/immersive_components/translations/en-us.json.json should be "en-us.json" instead of "en-us.json.json"

**Comment by SkyrimLL** [comment]
Thanks for the report but that's actually an oddity of Cyberpunk modding. The source file needs to be named with two .json extensions in order to the compressed json file used inside the package to be automatically named with only one .json extension.
